name: Run Pre-Commit via Flox

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - unstable
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

env:
  FLOX_DISABLE_METRICS: "true"

jobs:
  run-pre-commit:
    name: Run Pre-Commit
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-precommit
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/flox
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.flox/env/manifest.toml', '.flox/env/manifest.lock') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-${{ hashFiles('.flox/env/manifest.toml', '.flox/env/manifest.lock') }}
            pre-commit-${{ runner.os }}-${{ hashFiles('.flox/env/manifest.toml') }}
            pre-commit-${{ runner.os }}-

      - uses: flox/install-flox-action@a25f820b52f45ac0955289ccbb1184267b5abbe3 # v2.0.0
        with:
          channel: stable
          disable-metrics: true

      - name: Show Pre-Commit Version
        run: |
          set -o xtrace  # set -x # Print a trace of simple commands, for commands, case commands, select commands, and arithmetic for commands and their arguments or associated word lists after they are expanded and before they are executed. The value of the PS4 variable is expanded and the resultant value is printed before the command and its expanded arguments.

          echo "Checking available tools..."
          which flox || echo "flox not found in PATH."

          echo "Attempting to activate flox environment with timeout..."
          timeout 60 flox activate -- pre-commit --version || {
            echo "Failed to activate flox environment or run pre-commit."
            echo "Falling back to system pre-commit if available."
            which pre-commit && pre-commit --version || echo "No pre-commit found."
          }

      - name: Activate Flox Environment
        uses: flox/activate-action@d08556cc1491f3608f5338faf35cfa152dba3d5c # v1.0.0
        with:
          command: |
            set -o errexit  # set -e # Exit immediately if a pipeline, which may consist of a single simple command, a list, or a compound command returns a non-zero status.

            echo "Activating flox environment..."
            command -v flox >/dev/null && eval "$(flox activate)" || {
              echo "Failed to activate flox environment."
              exit 1
            }

            # Configure flox.
            flox config --set disable_metrics true

            # Install pre-commit environments if not cached.
            echo "Installing pre-commit hooks..."
            pre-commit install-hooks

            # Run pre-commit on all files for push to main branch, otherwise only on changed files.
            if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/unstable" ]]; then
              echo "Running pre-commit on all files (push to unstable branch)."
              pre-commit run --all-files
            else
              echo "Running pre-commit on changed files only."
              # For pull requests, run on files changed compared to the target branch.
              if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                pre-commit run --from-ref=origin/${{ github.base_ref }} --to-ref=HEAD
              else
                # For other events, run on all files as fallback.
                pre-commit run --all-files
              fi
            fi
